---
title: "Lee Pesky Learning Center Data Visualization"
author: "Luke Tuttle"
date: "2/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(siverse)
library(tidyverse)
```

```{r read_in_data, include = FALSE}
og_df <- read_excel("PreK_Implementation_Checklists.xlsx", sheet = "Form1") %>% 
  clean_names()
```

```{r create_question_groupings, include = FALSE}

q_list <- list("Alphabet Routines"  = colnames(og_df)[9:16],
               "Environmental Print Routines -- Name Recognition" = colnames(og_df)[27:33],
               "Environmental Print Routines -- Environmental Print" = colnames(og_df)[34:42],
               "Phonological Awareness Routines" = colnames(og_df)[c(43:50, 59:60)],
               "Language and Vocabulary: Read Aloud Routines" = colnames(og_df)[c(51:58, 61:62)],
               "Positive Climate" = colnames((og_df)[69:72]),
               "Behavior Management" = colnames((og_df)[74:77]),
               "Productivity" = colnames((og_df)[79:82]),
               "Language Modeling (REN)" = colnames((og_df)[84:87])
               )

#I have placed bleow a list of columns that we are interested in looking at just in case the column locations change and the above position-based code becomes unuseful. I used: str_c(unlist(q_list, use.names = FALSE), collapse = ", ") 

# "is_there_an_alphabet_displayed_at_an_appropriate_location_and_height, the_routine_includes_movement_and_an_engaging_voice, the_teacher_or_child_helper_points_to_and_says_each_letter, the_routine_lasts_no_longer_than_5_minutes, the_routine_is_done_at_least_2_times_during_the_day, x90_100_percent_of_children_are_participating_in_the_alphabet_routine, teacher_notices_and_encourages_students_to_participate_as_needed, teacher_points_out_letters_in_context_several_times_throughout_the_day, there_are_opportunities_for_children_to_recognize_their_names, scaffolding_is_provided_if_needed, children_have_at_least_2_opportunities_to_find_their_name_each_day, name_finding_recognition_routine_is_no_more_than_5_minutes, x90_100_percent_of_children_are_participating_in_the_name_recognition_routine, x90_100_percent_of_children_are_participating_in_the_alphabet_routine2, teacher_notices_and_encourages_students_to_participate_as_needed2, one_new_sign_is_introduced_each_week, teacher_reads_the_word_and_connects_meaning_to_the_word, teacher_points_out_letters_in_context_several_times_throughout_the_day2, children_say_the_word_with_the_teacher, sign_of_the_week_routine_is_no_more_than_2_4_minutes, x90_100_percent_of_children_are_participating_in_the_environmental_print_routine, teacher_notices_and_encourages_students_to_participate_as_needed6, teacher_notices_and_encourages_students_to_participate_as_needed3, teacher_points_out_letters_in_context_several_times_throughout_the_day3, teacher_selects_a_game_from_the_training_manual, game_is_practiced_multiple_days_in_a_row_or_until_game_is_well_rehearsed, teacher_incorporates_a_new_game_or_moves_to_next_skill_level_when_needed_to_maintain_student_interest, games_are_taught_as_described_in_the_training_manual, a_game_is_taught_every_day, a_phonological_awareness_skill_is_explicitly_taught_e_g_rhyming, phonological_awareness_activity_takes_between_2_8_minutes, x90_100_percent_of_children_are_participating_in_the_games, teacher_has_a_variety_of_books_to_read_to_children, teacher_selects_a_book_to_read_that_provides_rich_opportunities_for_vocabulary_development, teacher_has_identified_words_to_talk_about_ahead_of_time_evidence_of_this_includes_sticky_notes_highlights_planning_form, words_that_will_expand_a_child_s_vocabulary_are_used_at_least_2, teacher_says_the_word, children_repeat_the_word, teacher_explains_the_meaning_of_the_word_and_or_points_to_the_illustrations_to_help_children_understand_the_words, teacher_gives_an_example_of_the_word_e_g_glue_is_something_that_is_sticky_what_else_is_sticky_children_give_examples, children_say_the_word_again, x90_100_percent_of_children_are_participating_in_the_games2, relationships_proximity_shared_activities_social_conversations, positive_affect_smiling_laughter_enthusiasm, positive_communication_high_expectations, respect_respectful_language_cooperation_sharing_encouraged, clear_behavior_expectations, redirection_of_misbehavior, proactive_anticipates_problem_behavior, monitors, maximizes_learning_time, routines_children_know_what_to_do_clear_instructions, transitions_brief_follow_through_learning_opportunities, preparation_materials_are_ready_teacher_prepared_for_lesson, frequent_conversations_exchanges_contingent_responding_peer_conversations, open_ended_questions_more_than_a_one_word_response, repetition_and_extension_repeats_extends_elaborates, narrates_or_uses_self_talk_and_parallel_talk_e_g_i_am_getting_my_book_out_so_we_are_ready_to_read_louis_you_painted_the_house_in_your_picture_red_and_blue"


```


```{r cleaninng, include = FALSE}
trimmed <- og_df %>% 
  select(observer, classroom, mj_nampa_classrooms, mj_caldwell_classrooms, mj_west_bonner_classrooms, t_classrooms, unlist(q_list, use.names = FALSE), visit_number)
#Among all the columns containing  "classroom" there should only be one value per line, line 3 however has a value in 2 columns therefore I'm deleting one of the values prior to unite()'ing the columns into one. I think Glenda's day care belongs to the line above with Lori but Wissam wants me to leave it blank to illustrate a point about being careful with handling data to the client. 
trimmed[3,2] <- NA
trimmed[2,2] <- "Missing Teacher"

#create a single clasroom column
trimmed <- trimmed %>% 
  mutate_at(.vars = vars(contains("classroom")),
            .funs = funs(case_when(
              is.na(.) ~ "",
              TRUE ~ as.character(.))
            )
  ) %>% 
  unite(col = classroom, classroom:t_classrooms, sep = "")

#put visit number in third spot where it makes sense
trimmed <- trimmed %>% select(observer, classroom, visit_number, everything())


# convert all NAs and empty strings to "0" and make values uniform
trimmed <- trimmed %>% 
  mutate_all(.funs = funs(
    case_when(
      is.na(.) ~ "0",
      . == "" ~ "0",
      . == "9" ~ "0",
      . == "Low 1" ~ "1",
      . == "weak" ~ "1",
      . == "Medium 2" ~ "2",
      . == "High 3" ~ "3",
      TRUE ~ as.character(.)
    )
  ))



#considered seperating classroom column into school and teacher but most schools only have a one teacher

# make data long
trimmed <- gather(trimmed, "question", "performance", 4:61)

# create a question type variable in order to use when doing data vis
trimmed <- trimmed %>% mutate(question_type = 
  case_when(
    question %in% q_list$`Alphabet Routines` ~ "Alphabet Routines",
    question %in% q_list$`Environmental Print Routines -- Name Recognition` ~ "Environmental Print Routines -- Name Recognition",
    question %in% q_list$`Environmental Print Routines -- Environmental Print` ~ "Environmental Print Routines -- Environmental Print",
    question %in% q_list$`Phonological Awareness Routines` ~ "Phonological Awareness Routines",
    question %in% q_list$`Language and Vocabulary: Read Aloud Routines` ~ "Language and Vocabulary: Read Aloud Routines",
    question %in% q_list$`Positive Climate` ~ "Positive Climate",
    question %in% q_list$`Behavior Management` ~ "Behavior Management",
    question %in% q_list$Productivity ~ "Productivity",
    question %in% q_list$`Language Modeling (REN)` ~ "Language Modeling (REN",
    TRUE ~ as.character(question)
  )
) %>% 
  arrange(classroom, observer, visit_number, question_type)

```

```{r data_vis_func, include = FALSE, echo = FALSE, warning= FALSE}
# MODEL TO BASE FUNCTION OF OFF MORE OR LESS
# trimmed %>% 
#   filter(classroom == trimmed$classroom[1]) %>% 
#   filter(question_type == "red") %>% 
#   mutate(question = 
#            str_replace_all(question, "_", " ")) %>% 
#   ggplot(aes(x = question, y = performance, fill = visit_number)) + 
#   geom_col(position = "dodge") +
#   scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
#   scale_fill_discrete(guide = guide_legend("dkdkd"))
#   
# 
# 
# 


# THIS FUNCTION ALLOWS TO PLOT A SINGLE PLOT BY FEEDING IN THE CLASSROOM AND QUESTION TYPE AS STRINGS.

data_vis <- function(df, classroom, question_type) {
  class <- enquo(classroom)
  type <- enquo(question_type)
  
  df %>% 
    filter(classroom == !! class) %>% 
    filter(question_type == !! type) %>% 
    mutate(question = 
             str_replace_all(question, "_", " ")) %>% 
    ggplot(aes(x = question, y = performance, fill = visit_number)) + 
    geom_col(position = "dodge") +
    scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
    scale_fill_discrete(palette = viridis, guide = guide_legend("Visit Number")) +
    labs(title = classroom,
         subtitle = str_to_upper(question_type),
         x = paste0(str_to_title(question_type), " Question"),
         y = "Performance") 
  
}
    
q_colors <- names(q_list)

data_vis_loop <- function(x, y) {
  for (i in q_colors) {
  plot <- data_vis(x, y, i)
  print(plot)
  }
}

# OTHER THAN THE DATA SET, ALL YOU NEED TO DO IS PUT IN THE STRING FOR THE CLASSROOM
data_vis_loop(trimmed, "Canyonside Christian School -- Allison Cole")


data_vis_loop_all <- function(df, x) {
    for (i in x) {
    data_vis_loop(df, i)
    }
  }



```


```{r echo=FALSE}
data_vis_loop_all(trimmed, unique(trimmed$classroom)[1:68])
```


